### ISSUE TITLE
Tags with 8 byte IDs aren't decoded properly

### ISSUE THREAD

**Issue by mastahyeti** [cabo/cbor-ruby#12]
Shorter IDs seem to work, but 8 byte IDs are are totally garbled. This is a simple example

```ruby
CBOR.decode(CBOR::Tagged.new(0xDEADBEEFDEADBEEF, 1).to_cbor).tag == 0xDEADBEEFDEADBEEF
# => false
```

**Comment by cabo** [comment]
Confirmed.  Code is missing for handling bignum tag numbers (more than 62 bits), or any type check on the tag number at all, actually.  I should be able to fix this today.

**Comment by mastahyeti** [comment]
Thanks!
