### ISSUE TITLE
Decoding Concatenated CBOR Objects

### ISSUE THREAD

**Issue by sumitbirla** [cabo/cbor-ruby#23]
Is it possible to decode a byte array that contains more than one concatenated CBOR object?   It throws the following exception:

`CBOR.decode(bytes)`

`CBOR::MalformedFormatError (extra bytes follow after a deserialized object)`

**Comment by cabo** [comment]
On 18. Jun 2024, at 00:22, Sumit Birla ***@***.***> wrote:
> 
> 
> Is it possible to decode a byte array that contains more than one concatenated CBOR object? It throws the following exception:
> CBOR.decode(bytes)
> CBOR::MalformedFormatError (extra bytes follow after a deserialized object)

Yes.
You’ll need to use a slightly lower level API:

u = CBOR::Unpacker.new
u.feed_each("DalekDalekDis") {|x| p x}
u.feed_each("co") {|x| p x}

(“D” is 0x44, so CBOR.decode(“Dalek”) is the byte string “alek”.

There are separate #feed and #each methods if that helps.

Grüße, Carsten

**Comment by sumitbirla** [comment]
Thanks!  That does the trick.
