### ISSUE TITLE
CBOR.load(CBOR.dump(1234)) returns 13763794

### ISSUE THREAD

**Issue by larsch** [cabo/cbor-ruby#3]
```
C:\>irb
irb(main):001:0> require 'cbor'
=> true
irb(main):002:0> CBOR.load(CBOR.dump(1234))
=> 13763794

C:\>ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
```

**Comment by cabo** [comment]
Whoa.  Obviously, I can't reproduce this on Ruby 2.2.4.
What is the output of

```
CBOR.dump(1234)
```

?

It should be
```
"\x19\x04\xD2"
```

**Comment by larsch** [comment]
Looks ok:
```
irb(main):002:0> CBOR.dump(1234)
=> "\x19\x04\xD2"
```

Seem to be bad for all 16 bit numbers, except multiples of 256.
```
257..511 bad
513..767 bad
769..1023 bad
1025..1279 bad
1281..1535 bad
1537..1791 bad
1793..2047 bad
2049..2303 bad
2305..2559 bad
2561..2815 bad
2817..3071 bad
3073..3327 bad
3329..3583 bad
3585..3839 bad
3841..4095 bad
4097..4351 bad
4353..4607 bad
4609..4863 bad
...
```

**Comment by larsch** [comment]
Notice how the LSB byte is repeated:

```
irb(main):006:0> "%02x" % CBOR.load(CBOR.dump(257))
=> "10101"
irb(main):007:0> "%02x" % CBOR.load(CBOR.dump(257))
=> "10101"
irb(main):008:0> "%02x" % CBOR.load(CBOR.dump(1234))
=> "d204d2"
irb(main):009:0> "%02x" % CBOR.load(CBOR.dump(7514))
=> "5a1d5a"
```

This bit of code seems suspicious:

```c
/* _msgpack_be16 */
#ifdef _WIN32
#  if defined(ntohs)
#    define _msgpack_be16(x) ntohs(x)
#  elif defined(_byteswap_ushort) || (defined(_MSC_VER) && _MSC_VER >= 1400)
#    define _msgpack_be16(x) ((uint16_t)_byteswap_ushort((unsigned short)x))
#  else
#    define _msgpack_be16(x) ( \
        ((((uint16_t)x) <<  8) ) | \
        ((((uint16_t)x) >>  8) ) )
#  endif
#else
#  define _msgpack_be16(x) ntohs(x)
#endif 
```

The third option doesn't mask the resulting 16 bits leaving the LSB bits in bit 17-24.

**Comment by cabo** [comment]
Thanks for the pointer to the broken code (I had no idea that msgpack, from which I borrowed this code, does not work on mingw).
0.5.9.1 should fix this.  I would be grateful if you could run the tests for me; I don't have easy access to a Windows development environment.  I will cut a new gem when I have your confirmation.

**Comment by larsch** [comment]
That works! I ran my set of tests for my serialization comparison and it passed without issues (I was writing my own before I discovered CBOR...) Thanks for the speedy response and fix!

**Comment by cabo** [comment]
Thank you for the confirmation.  I just pushed 0.5.9.1.
