### ISSUE TITLE
Support for canonical cbor

### ISSUE THREAD

**Issue by jkbbwr** [cabo/cbor-ruby#4]
Does this support canonical cbor like the Go implementation does?

**Comment by cabo** [comment]
I haven't had a use case for canonical CBOR yet, so I haven't looked into this.
Obviously, the output already is "mostly canonical" (except for map ordering -- my implementation uses Ruby enumeration order here).  Note that Section 3.9 of RFC 7049 does not tell you exactly what to do about floating point values, but the implementation follows the suggestions here.

So if you need to do canonical now, you could reorder your maps (yes, Ruby Hashes have order) before feeding them into the CBOR encoder.  Is that "Support" enough for your use case?

**Comment by jkbbwr** [comment]
It would be nice for the map sorting to happen based on an argument in the library, the whole point of having it done by the library would be to reduce confusion about implementing the key sorting. 

This means that I can have people execute `{}.to_canonical_cbor`

And I will be able to sha256 that in ruby and get the same hash in python

**Comment by cabo** [comment]
That sure would be nice, but what's the use case you have in mind for this?
The implementation would need to sort the keys (with the somewhat weird sorting order) based on their CBOR representations, and then put together the whole encoding.  Isn't that easier to program in Ruby?

**Comment by cabo** [comment]
https://gist.github.com/cabo/2d0591640d6e92b4ee701514ffeb12f2

**Comment by jkbbwr** [comment]
Cryptographic hashing of arbitrary data structures between languages. Can the ruby wrapper live inside the library? It becomes a simple work flow for someone to create a client for my product that requires client side hashing of data, it becomes very simple for someone to `require "cbor"` and then just call this canonical method. Then they will produce the same cbor output as any other language or platform.

I foresee this becoming a _killer_ feature of cbor.

**Comment by cabo** [comment]
Now covered by the [cbor-canonical](https://github.com/cabo/cbor-canonical) gem.

`gem install cbor-canonical`

This doesn't mean that canonicalization is now somehow wonderful -- I would still recommend to avoid depending on it.  It is usually much better to hash the byte strings being exchanged instead of relying on both sides of an exchange to generate the same byte strings.
