### ISSUE TITLE
adding CBOR tags

### ISSUE THREAD

**Issue by mcr** [cabo/cbor-ruby#8]
Can you point to an ruby example of adding a specific (arbitrary) tag in front of a specific integer?
Should I create a class with a custom to_cbor for it, and then... what would I do?

**Comment by cabo** [comment]
If your code is aware that it is dealing with CBOR tags and there is no need for a class for any other reason, CBOR::Tagged is the right structure to use:

```
>> ti = CBOR::Tagged.new(4711, 12345678)
=> #<struct CBOR::Tagged tag=4711, value=12345678>
>> ti.to_cbor
=> "\xD9\x12g\x1A\x00\xBCaN"
```

If your code is already defining a class to associate some behavior to the object, just add a to_cbor method to that class.  If you are using an existing class, you can mix in a module to that like I did for DateTime in https://gist.github.com/cabo/fb2f6ea30f1158b63e6c5649beabfc75 (assuming that there aren't going to be other pieces of code that use the same class with a different CBOR representation).
